### ISSUE TITLE
Enhancement: Show in Movies/Shows of the Kodi menu

### ISSUE THREAD

**Issue by siteripper** [HackerspaceBielefeld/plugin.video.streama#2]
Hello,

it would be great if the addon autostarts on Kodi -Startup and shows the Movies/Shows directly in the Kodi main menues. (so that you dont have to go to Addons->Streama->Movies)

Greets,

siteripper

**Comment by bodems** [comment]
I don't think that is possible directly within the addon, but there is something in Kodi called autoexec.py, so you can start it with that: http://kodi.wiki/view/Autoexec.py
