### ISSUE TITLE
Error with Streama v1.4.1 RC

### ISSUE THREAD

**Issue by siteripper** [HackerspaceBielefeld/plugin.video.streama#5]
With new streama version I get this error when trying to open movies folder:

15:30:48.658 T:3748   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers
                                            Traceback (most recent call last):
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.streama\addon.py", line 283, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.streama\addon.py", line 266, in router
                                                list_videos(params['category'], params['showid'])
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.streama\addon.py", line 158, in list_videos
                                                list_item = xbmcgui.ListItem(label=video['title'])
                                            TypeError: string indices must be integers
                                            -->End of Python script error report<--
15:30:48.670 T:68   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.streama/?action=listing&category=Filme&showid=0
15:30:48.671 T:68   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streama/?action=listing&category=Filme&showid=0) failed

**Comment by joen** [comment]
Thanks for your report, @siteripper. As we use streama 1.3.3 beta, we can currently not test against this error, but a restructuring is (somewhat) in the works ... We could use some help, too, so if you would like to contribute, feel free to fork, comment and bug report.

**Comment by bodems** [comment]
I can confirm this with 1.4.2, will try to fix it

**Comment by bodems** [comment]
Should work again with streama 1.4.x, see commit f750330b2085d9d9b5e7cd7bb6d2fa4e94c29362

**Comment by Niach** [comment]
@bodems movies and series work now, but new releases and search dont work anymore (1.4.2)

**Comment by bodems** [comment]
Fixed in a0b7a2073279c5b684da3a7e6d29b0fedbe980d8. Movies, series, new releases and search should work again with 1.4.2. Meanwhile 1.5.0 is out, let me know if it doesn't work with it.
Thanks for your hint @Niach

**Comment by Niach** [comment]
works with 1.5.0
edit: video playback does not work with 1.5.0

**Comment by Niach** [comment]
works with 1.5.0

**Comment by Niach** [comment]
works with 1.5.0
