### ISSUE TITLE
Issues with 1.5.1

### ISSUE THREAD

**Issue by Niach** [HackerspaceBielefeld/plugin.video.streama#7]
Video playback and episode listing does not work with streama 1.5.x

**Comment by bodems** [comment]
Oh yes, baseurl was removed in videofile src, so kodi fails to play videos. Fix for that is in 4a1938158212c6ce4ff5b26ded482a63aca63139
For episode listing I have to investigate.

**Comment by bodems** [comment]
Episode listing is also fixed: f3c440552098dc7991143c3d4511623393eef96b

**Comment by Niach** [comment]
Thanks! Works like a charm 👍
